---
title: "Reading Delimited Data"
author: "Shohn Godboldt"
editor: visual
---
# Load Libraries

```{r}
library(tidyverse)
library(readxl)
```
#  Task 2: Reading Delimited Data

## Glass Data

```{r}
# Read glass data from a URL, using commas as delimiters
glass_data <- read_delim(
"https://www4.stat.ncsu.edu/~online/datasets/glass.data",
delim = ",",
col_names = c("Id", "RI", "Na", "Mg", "Al", "Si", "K", "Ca", "Ba", "Fe", "Type_of_glass")
)

# Recode numeric Type_of_glass into descriptive categories
glass_data <- glass_data %>%
mutate(
Type_of_glass = case_when(
Type_of_glass == 1 ~ "building_windows_float_processed",
Type_of_glass == 2 ~ "building_windows_non_float_processed",
Type_of_glass == 3 ~ "vehicle_windows_float_processed",
Type_of_glass == 5 ~ "containers",
Type_of_glass == 6 ~ "tableware",
Type_of_glass == 7 ~ "headlamps"
)
)

# View transformed data
glass_data
```

## Yeast Data

```{r}
# Read space-delimited yeast data using read_table()
yeast_data <- read_table(
"https://www4.stat.ncsu.edu/~online/datasets/yeast.data",
col_names = c("seq_name", "mcg", "gvh", "alm", "mit", "erl", "pox", "vac", "nuc", "class")
)

# Summarize mean and median for selected columns, grouped by 'class'
yeast_summary <- yeast_data %>%
select(-seq_name, -nuc) %>% # Remove columns not needed for summary
group_by(class) %>%
summarise(
across(mcg:vac, list(mean = mean, median = median), .names = "{.col}_{.fn}")
)

# View summary statistics
yeast_summary
```
---
